### ISSUE TITLE
[Bug] java.lang.AssertionError: Reentrant indexing

### ISSUE THREAD

**Issue by carlos-reynosa** [Atwix/phpstorm-plugin-feedback#10]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
java.lang.AssertionError: Reentrant indexing
	at com.intellij.util.indexing.FileBasedIndexImpl.markFileIndexed(FileBasedIndexImpl.java:1710)
	at com.intellij.util.indexing.FileBasedIndexImpl.createSingleIndexValueApplier(FileBasedIndexImpl.java:1602)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1563)
	at com.intellij.util.indexing.FileBasedIndexImpl.scheduleFileForIndexing(FileBasedIndexImpl.java:1880)
	at com.intellij.util.indexing.events.ChangedFilesCollector.lambda$processFilesToUpdateInReadAction$3(ChangedFilesCollector.java:231)
	at com.intellij.util.indexing.events.ChangedFilesCollector.lambda$processFilesInReadAction$4(ChangedFilesCollector.java:255)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:628)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at com.intellij.util.indexing.events.ChangedFilesCollector.lambda$processFilesInReadAction$5(ChangedFilesCollector.java:254)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:233)
	at com.intellij.util.indexing.events.ChangedFilesCollector.lambda$processFilesInReadAction$6(ChangedFilesCollector.java:252)
	at com.intellij.util.indexing.events.VfsEventsMerger.processChanges(VfsEventsMerger.java:94)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesInReadAction(ChangedFilesCollector.java:251)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesToUpdateInReadAction(ChangedFilesCollector.java:227)
	at com.intellij.util.indexing.events.ChangedFilesCollector.ensureUpToDate(ChangedFilesCollector.java:193)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:766)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:322)
	at com.intellij.util.indexing.FileBasedIndexEx.getFileData(FileBasedIndexEx.java:213)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFileData(FileBasedIndexImpl.java:1089)
	at com.intellij.util.indexing.FileBasedIndexEx.getSingleEntryIndexData(FileBasedIndexEx.java:234)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:121)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:49)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:634)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:956)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStub(PsiFileImpl.java:611)
	at com.jetbrains.php.lang.psi.PhpPsiUtil.findClasses(PhpPsiUtil.java:566)
	at com.jetbrains.php.lang.psi.PhpPsiUtil.findAllClasses(PhpPsiUtil.java:602)
	at com.atwix.magento.lang.php.util.PhpClassReaderUtil.getFirstClassOfFile(PhpClassReaderUtil.kt:28)
	at com.atwix.magento.framework.test.MagentoTestSourceVerifier.isTestSource(MagentoTestSourceVerifier.java:118)
	at com.atwix.magento.framework.test.MagentoTestSourceVerifier.isTestSource(MagentoTestSourceVerifier.java:111)
	at com.atwix.magento.project.configurator.MagentoTestSourceFilterService.isTestSource(MagentoTestSourceFilterService.java:33)
	at com.intellij.openapi.roots.TestSourcesFilter.isTestSources(TestSourcesFilter.java:31)
	at com.pestphp.pest.PhpTestFolderInputFilter.acceptInput(PhpTestFolderInputFilter.kt:16)
	at com.pestphp.pest.features.datasets.DatasetIndex$getInputFilter$1.acceptInput(DatasetIndex.kt:67)
	at com.intellij.util.indexing.FileBasedIndexEx$1.acceptInput(FileBasedIndexEx.java:826)
	at com.intellij.util.indexing.FileBasedIndexEx.acceptsInput(FileBasedIndexEx.java:813)
	at com.intellij.util.indexing.FileBasedIndexImpl.acceptsInput(FileBasedIndexImpl.java:1983)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$scheduleFileForIndexing$31(FileBasedIndexImpl.java:1902)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:670)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:653)
	at com.intellij.util.indexing.FileBasedIndexImpl.scheduleFileForIndexing(FileBasedIndexImpl.java:1895)
	at com.intellij.util.indexing.events.ChangedFilesCollector.lambda$processFilesToUpdateInReadAction$3(ChangedFilesCollector.java:231)
	at com.intellij.util.indexing.events.ChangedFilesCollector.lambda$processFilesInReadAction$4(ChangedFilesCollector.java:255)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.co
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2023/02/17
 - Plugin version: 2023.1.0
 - PhpStorm version: 2022.3.2 (PS-223.8617.59)
 - OS version: Linux 5.15.93-1-manjaro

**Comment by bohdan-harniuk** [comment]
Hello, @carlos-reynosa!

Thank you for your report!
Could you please describe steps to reproduce to solve this issue faster?

Regards,

**Comment by bohdan-harniuk** [comment]
Hello, @carlos-reynosa!

I cannot reproduce this issue.
Do you still have this issue on your environment?

Regards,

**Comment by carlos-reynosa** [comment]
I honestly don't know what the issue has been but since I had installed the plugin phpstorm has been crashing a lot. What I did was increase the max memory for phpstorm to 8GB and enabled the plugin again. I haven't noticed any crashes yet. And just to note I have both the the Magento open source plugin and this plugin installed. I'm ok with this being closed. I just wanted to report for visibility.

**Comment by bohdan-harniuk** [comment]
This plugin does not use more memory than IDE itself. I can see from the stack trace that issue occurred during reindex, but I couldn’t reproduce it even while running different processes with indexing on background. This stack trace is shortened by the bug reporting feature because of GitHub limitations. Could you please try to reproduce this issue again and copy & paste full stack trace with more details? It would help a lot.

**Comment by carlos-reynosa** [comment]
I'm not sure what the problem is but every time i keep enabling this plugin my IDE just freezes and become unusable. Sometimes I don't even get an error. I have had to disable the plugin for now and i'll check back in the next update. I'm runing Manjaro Linux with phpstorm installed via  Snap. Thanks!

**Comment by bohdan-harniuk** [comment]
I don't sure about core issue with your freezes, but I can try to help you here. If you want me to help you, let's schedule meeting. What do you think?

**Comment by carlos-reynosa** [comment]
This issue is resolved for me. It turns out to have been a bigger issue with my system. Closing. Thanks!
