### ISSUE TITLE
[Bug] java.lang.Exception

### ISSUE THREAD

**Issue by Nico2P** [Atwix/phpstorm-plugin-feedback#19]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
Outdated stub in index: file:///opt/magento2/generated/code/Magento/Quote/Model/Quote/AddressFactory.php indexing timestamp = 1680264533085, binary = false, byte size = 1094, char size = 1094, doc=DocumentImpl[file:///opt/magento2/generated/code/Magento/Quote/Model/Quote/AddressFactory.php], docSaved=true, wasIndexedAlready=true, queried at 1680264533085
doc length=0
file length=1094
cached PSI class com.jetbrains.php.lang.psi.PhpFileImpl
projects with file: 1
physical file doesn't exist; length = /opt/magento2/generated/code/Magento/Quote/Model/Quote/AddressFactory.php

java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:191)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:157)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:124)
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:64)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:190)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:138)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:215)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:734)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:128)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getFirstChild(ASTDelegatePsiElement.java:99)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:32)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:14)
	at com.intellij.util.WalkingState.next(WalkingState.java:70)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:58)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:62)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:924)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:76)
	at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:920)
	at com.intellij.psi.util.PsiTreeUtil.findChildrenOfAnyType(PsiTreeUtil.java:316)
	at com.intellij.psi.util.PsiTreeUtil.findChildrenOfType(PsiTreeUtil.java:281)
	at com.atwix.magento.feature.plugin.inspection.PluginCyclicCallLoopInspection.stepIntoMethod(PluginCyclicCallLoopInspection.kt:116)
	at com.atwix.magento.feature.plugin.inspection.PluginCyclicCallLoopInspection.findWrappedMethodCalls(PluginCyclicCallLoopInspection.kt:96)
	at com.atwix.magento.feature.plugin.inspection.PluginCyclicCallLoopInspection.findWrappedMethodCalls(PluginCyclicCallLoopInspection.kt:103)
	at com.atwix.magento.feature.plugin.inspection.PluginCyclicCallLoopInspection.findWrappedMethodCalls(PluginCyclicCallLoopInspection.kt:103)
	at com.atwix.magento.feature.plugin.inspection.PluginCyclicCallLoopInspection.findWrappedMethodCalls(PluginCyclicCallLoopInspection.kt:103)
	at com.atwix.magento.feature.plugin.inspection.PluginCyclicCallLoopInspection.findWrappedMethodCalls(PluginCyclicCallLoopInspection.kt:103)
	at com.atwix.magento.feature.plugin.inspection.PluginCyclicCallLoopInspection.findWrappedMethodCalls(PluginCyclicCallLoopInspection.kt:103)
	at com.atwix.magento.feature.plugin.inspection.PluginCyclicCallLoopInspection.findWrappedMethodCalls(PluginCyclicCallLoopInspection.kt:103)
	at com.atwix.magento.feature.plugin.inspection.PluginCyclicCallLoopInspection.findWrappedMethodCalls$default(PluginCyclicCallLoopInspection.kt:73)
	at com.atwix.magento.feature.plugin.inspection.PluginCyclicCallLoopInspection$buildVisitor$1.visitPhpMethodReference(PluginCyclicCallLoopInspection.kt:55)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:44)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$9(InspectionRunner.java:324)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:332)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:173)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:338)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:301)
	at com.intellij.util.As
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2023/03/31
 - Plugin version: 2023.2.1/F
 - PhpStorm version: 2022.3.3 (PS-223.8836.42)
 - OS version: Linux 5.19.0-38-generic

**Comment by bohdan-harniuk** [comment]
Hello, @Nico2P!

Thank you for your report!

**Comment by bohdan-harniuk** [comment]
Hi @Nico2P,

I apologize for the delayed response. We attempted to reproduce the issue multiple times, but without success. After some time, we sought assistance from the JetBrains (PHP-related) team. It turned out that this issue is connected to PHPStorm's native functionality and shouldn't impact anything critically important. Invalidate caches should always resolve it: https://www.jetbrains.com/help/phpstorm/invalidate-caches.html

Please, reopen this issue if you need more help here.
Regards,
