### ISSUE TITLE
[Bug] java.lang.Exception

### ISSUE THREAD

**Issue by FryingDutch** [Atwix/phpstorm-plugin-feedback#21]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
Outdated stub in index: file:///Users/jan/repos/didi/app/code/Etales/FlektoPostcode/registration.php indexing timestamp = 1681285181754, binary = false, byte size = 170, char size = 170, doc=DocumentImpl[file:///Users/jan/repos/didi/app/code/Etales/FlektoPostcode/registration.php], docSaved=true, wasIndexedAlready=true, queried at 1681285181754
doc length=0
file length=170
cached PSI class com.jetbrains.php.lang.psi.PhpFileImpl
projects with file: 1
physical file doesn't exist; length = /Users/jan/repos/didi/app/code/Etales/FlektoPostcode/registration.php

java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:191)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:157)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:124)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:49)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:634)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:956)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStub(PsiFileImpl.java:611)
	at com.jetbrains.php.lang.psi.PhpPsiUtil.findClasses(PhpPsiUtil.java:566)
	at com.jetbrains.php.lang.psi.PhpPsiUtil.findAllClasses(PhpPsiUtil.java:602)
	at com.atwix.magento.lang.php.util.PhpClassReaderUtil.getFirstClassOfFile(PhpClassReaderUtil.kt:32)
	at com.atwix.magento.framework.test.MagentoTestSourceVerifier.isTestSource(MagentoTestSourceVerifier.java:118)
	at com.atwix.magento.framework.test.MagentoTestSourceVerifier.isTestSource(MagentoTestSourceVerifier.java:111)
	at com.atwix.magento.project.configurator.MagentoTestSourceFilterService.isTestSource(MagentoTestSourceFilterService.java:33)
	at com.intellij.openapi.roots.TestSourcesFilter.isTestSources(TestSourcesFilter.java:31)
	at com.intellij.psi.search.scope.TestsScope$1.contains(TestsScope.java:25)
	at com.intellij.psi.search.scope.packageSet.FilteredPackageSet.contains(FilteredPackageSet.java:22)
	at com.intellij.ui.tabs.FileColorsModel.findConfiguration(FileColorsModel.java:239)
	at com.intellij.ui.tabs.FileColorsModel.getColor(FileColorsModel.java:210)
	at com.intellij.ui.tabs.FileColorManagerImpl.getFileColor(FileColorManagerImpl.java:167)
	at com.intellij.ui.tabs.EditorTabColorProviderImpl.getProjectViewColor(EditorTabColorProviderImpl.java:41)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getFileBackgroundColor(EditorTabPresentationUtil.java:66)
	at com.intellij.usages.UsageInfo2UsageAdapter.computeBackgroundColor(UsageInfo2UsageAdapter.java:118)
	at com.intellij.usages.UsageInfo2UsageAdapter.doUpdateCachedPresentation(UsageInfo2UsageAdapter.java:484)
	at com.intellij.usages.UsageInfo2UsageAdapter.getIcon(UsageInfo2UsageAdapter.java:545)
	at com.intellij.find.impl.FindInProjectExecutor.findUsages$lambda-0(FindInProjectExecutor.kt:36)
	at com.intellij.find.impl.FindInProjectTask.lambda$processFindInFilesUsagesInFile$10(FindInProjectTask.java:267)
	at com.intellij.find.impl.FindInProjectUtil.lambda$processUsagesInFile$2(FindInProjectUtil.java:249)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:873)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.find.impl.FindInProjectUtil.processUsagesInFile(FindInProjectUtil.java:249)
	at com.intellij.find.impl.FindInProjectTask.processFindInFilesUsagesInFile(FindInProjectTask.java:256)
	at com.intellij.find.impl.FindInProjectTask.lambda$wrapUsageProcessor$6(FindInProjectTask.java:207)
	at com.intellij.find.impl.FindInProjectTask.lambda$findUsages$5(FindInProjectTask.java:166)
	at com.intellij.find.impl.FindInProjectTask.lambda$processFilesInScope$18(FindInProjectTask.java:403)
	at com.intellij.openapi.roots.impl.FilesScanExecutor$doProcessOnAllThreadsInReadAction$1.invoke$lambda-0(FilesScanExecutor.kt:90)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:109)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)

```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2023/04/12
 - Plugin version: 2023.2.1/F
 - PhpStorm version: 2022.3 (PS-223.7571.212)
 - OS version: macOS 12.3.1

**Comment by bohdan-harniuk** [comment]
Hello, @FryingDutch!

Thank you for your report.
