### ISSUE TITLE
[Bug] java.lang.Exception

### ISSUE THREAD

**Issue by xaevik** [Atwix/phpstorm-plugin-feedback#34]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
Outdated stub in index: file:////wsl$/Ubuntu/home/abrault/Sites/hardwareandtools-com/generated/code/Magento/CatalogRule/Model/Rule/Interceptor.php indexing timestamp = 1692034881362, binary = false, byte size = 3940, char size = 3940, doc=DocumentImpl[file:////wsl$/Ubuntu/home/abrault/Sites/hardwareandtools-com/generated/code/Magento/CatalogRule/Model/Rule/Interceptor.php], docSaved=true, wasIndexedAlready=true, queried at 1692034881362
doc length=0
file length=0
cached PSI class com.jetbrains.php.lang.psi.PhpFileImpl
PSI length=0
projects with file: 1
physical file doesn't exist; length = \\wsl$\Ubuntu\home\abrault\Sites\hardwareandtools-com\generated\code\Magento\CatalogRule\Model\Rule\Interceptor.php

java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:191)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:157)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:124)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.doCreateCompleteException(StubTreeLoader.java:192)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.access$300(StubTreeLoader.java:151)
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:72)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:151)
	at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:93)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:72)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:146)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:210)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:90)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:740)
	at com.jetbrains.php.PhpIndexImpl.getDirectSubclassesInner(PhpIndexImpl.java:777)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.jetbrains.php.PhpIndexImpl.getDirectSubclasses(PhpIndexImpl.java:773)
	at com.jetbrains.php.PhpIndexImpl.fillAllSubclasses(PhpIndexImpl.java:795)
	at com.jetbrains.php.PhpIndexImpl.fillAllSubclasses(PhpIndexImpl.java:797)
	at com.jetbrains.php.PhpIndexImpl.fillAllSubclasses(PhpIndexImpl.java:797)
	at com.jetbrains.php.PhpIndexImpl.fillAllSubclasses(PhpIndexImpl.java:797)
	at com.jetbrains.php.PhpIndexImpl.getAllSubclasses(PhpIndexImpl.java:789)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.subClasses(MemberReferenceImpl.java:306)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.lambda$subclasses$9(MemberReferenceImpl.java:302)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at one.util.streamex.AbstractStreamEx.forEach(AbstractStreamEx.java:360)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.withSuperClasses(MemberReferenceImpl.java:289)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.lookInSubclasses(MemberReferenceImpl.java:279)
	at com.jetbrains.php.lang.psi.elements.impl.PhpBaseMemberReference.resolveGlobalDescriptors(PhpBaseMemberReference.java:68)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.resolveGlobalDescriptors(MethodReferenceImpl.java:105)
	at com.jetbrains.php.lang.psi.elements.impl.PhpBaseMemberReference.multiResolve(PhpBaseMemberReference.java:83)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.lambda$getResolver$2(PhpReferenceImpl.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:69)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:161)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.re
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2023/08/14
 - Plugin version: 2023.5.0/L
 - PhpStorm version: 2023.1.4 (PS-231.9225.18)
 - OS version: Windows 11.0

**Comment by bohdan-harniuk** [comment]
Hello, @xaevik!

Please, run reindex and try to reproduce this issue one more time. Provide the steps to reproduce. Thank you.

Regards,

**Comment by xaevik** [comment]
Hi @bohdan-harniuk this appears to be a race condition caused by an unrelated tool (Warden) so I'm going to go ahead and close this.
