### ISSUE TITLE
[Bug]   Unhandled exception in [CoroutineName(DocumentationBrowser requests), StandaloneCoroutine{Cancelling}@4f174b16, Dispatchers.Default]

### ISSUE THREAD

**Issue by tgamanov** [Atwix/phpstorm-plugin-feedback#35]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
*** exception class was changed or removed

  Unhandled exception in [CoroutineName(DocumentationBrowser requests), StandaloneCoroutine{Cancelling}@4f174b16, Dispatchers.Default]
  
  java.lang.UnsupportedOperationException: Method getParent is not yet implemented in com.atwix.magento.feature.i18n.reference.I18nReference$wrapPhraseInElement$1
at com.atwix.magento.lang.MockPsiElement.getParent(MockPsiElement.kt:174)
at com.intellij.psi.css.impl.util.CssUtil.isCssDeclaration(CssUtil.java:142)
at com.intellij.psi.css.impl.util.CssDocumentationProvider.findDocumentationElement(CssDocumentationProvider.java:180)
at com.intellij.psi.css.impl.util.CssDocumentationProvider.generateDoc(CssDocumentationProvider.java:229)
at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:135)
at com.intellij.xml.util.documentation.HtmlDocumentationProvider.generateDocFromStyleOrScript(HtmlDocumentationProvider.java:157)
at com.intellij.xml.util.documentation.HtmlDocumentationProvider.generateDoc(HtmlDocumentationProvider.java:77)
at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:135)
at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.localDocHtml(PsiElementDocumentationTarget.kt:112)
at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.localDoc(PsiElementDocumentationTarget.kt:97)
at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.doComputeDocumentation(PsiElementDocumentationTarget.kt:84)
at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.access$doComputeDocumentation(PsiElementDocumentationTarget.kt:28)
at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget$computeDocumentation$1.invoke(PsiElementDocumentationTarget.kt:78)
at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget$computeDocumentation$1.invoke(PsiElementDocumentationTarget.kt:77)
at com.intellij.openapi.progress.CoroutinesKt.jobToIndicator$lambda$1(coroutines.kt:386)
at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
at com.intellij.openapi.progress.CoroutinesKt.jobToIndicator(coroutines.kt:374)
at com.intellij.openapi.progress.CoroutinesKt.contextToIndicator(coroutines.kt:347)
at com.intellij.openapi.progress.CoroutinesKt.blockingContextToIndicator(coroutines.kt:340)
at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.computeDocumentation(PsiElementDocumentationTarget.kt:77)
at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2$documentationResult$1.invoke(impl.kt:29)
at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2$documentationResult$1.invoke(impl.kt:28)
at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:105)
at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:14)
at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:41)
at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:39)
at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:37)
at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:34)
at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:76)
at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:63)
at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:14)
at com.intellij.openapi.appl
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2023/08/23
 - Plugin version: 2023.5.0/F
 - PhpStorm version: 2023.2 (PS-232.8660.205)
 - OS version: Linux 6.2.0-26-generic

**Comment by bohdan-harniuk** [comment]
Hello @tgamanov,

Thank you for your report. Could you please provide steps to reproduce this bug?
It would be helpful if you attach content of the file for which that exception was risen. 

Regards,

**Comment by bohdan-harniuk** [comment]
Reproduced

**Comment by bohdan-harniuk** [comment]
**Fixed and Coming Soon!**

The reported bug has been fixed and will be available in our upcoming release. Thank you for bringing it to our attention! 

If you encounter any issues or have more feedback, please let us know.
