### ISSUE TITLE
[Bug]    Outdated stub in index: file:////wsl$/Ubuntu/home/bashev/magento/app/code/Webcode/Ui/registration.php indexing timestamp = 1671890439576, binary = false, byte size = 374, char size = 373, doc=DocumentImpl[file:////wsl$/Ubuntu/home/bashev/magento/app/code/Webcode/Ui/registration.php], docSaved=true, wasIndexedAlready=true, queried at 1671890439576

### ISSUE THREAD

**Issue by Bashev** [Atwix/phpstorm-plugin-feedback#37]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
*** exception class was changed or removed

   Outdated stub in index: file:////wsl$/Ubuntu/home/bashev/magento/app/code/Webcode/Ui/registration.php indexing timestamp = 1671890439576, binary = false, byte size = 374, char size = 373, doc=DocumentImpl[file:////wsl$/Ubuntu/home/bashev/magento/app/code/Webcode/Ui/registration.php], docSaved=true, wasIndexedAlready=true, queried at 1671890439576
doc length=0
file length=374
cached PSI class com.jetbrains.php.lang.psi.PhpFileImpl
projects with file: 1
physical file exists; length = 374
   
   java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:189)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:155)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:122)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:48)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:624)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:943)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStub(PsiFileImpl.java:602)
	at com.jetbrains.php.lang.psi.PhpPsiUtil.findClasses(PhpPsiUtil.java:567)
	at com.jetbrains.php.lang.psi.PhpPsiUtil.findAllClasses(PhpPsiUtil.java:603)
	at com.atwix.magento.lang.php.util.PhpClassReaderUtil.getFirstClassOfFile(PhpClassReaderUtil.kt:32)
	at com.atwix.magento.framework.test.MagentoTestSourceVerifier.isTestSource(MagentoTestSourceVerifier.java:118)
	at com.atwix.magento.framework.test.MagentoTestSourceVerifier.isTestSource(MagentoTestSourceVerifier.java:111)
	at com.atwix.magento.project.configurator.MagentoTestSourceFilterService.isTestSource(MagentoTestSourceFilterService.java:37)
	at com.intellij.openapi.roots.TestSourcesFilter.isTestSources(TestSourcesFilter.java:31)
	at com.intellij.psi.search.scope.TestsScope$1.contains(TestsScope.java:25)
	at com.intellij.psi.search.scope.packageSet.FilteredPackageSet.contains(FilteredPackageSet.java:22)
	at com.intellij.ui.tabs.FileColorsModel.findConfiguration(FileColorsModel.java:246)
	at com.intellij.ui.tabs.FileColorsModel.lambda$getColor$0(FileColorsModel.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.ui.tabs.FileColorsModel.getColor(FileColorsModel.java:211)
	at com.intellij.ui.tabs.FileColorManagerImpl.getFileColor(FileColorManagerImpl.java:166)
	at com.intellij.ui.tabs.EditorTabColorProviderImpl.getProjectViewColor(EditorTabColorProviderImpl.java:31)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getFileBackgroundColor(EditorTabPresentationUtil.kt:47)
	at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.getFileBackgroundColor(VfsPresentationUtil.java:48)
	at com.intellij.presentation.impl.FilePresentationServiceImpl.getFileBackgroundColor(FilePresentationServiceImpl.kt:22)
	at com.intellij.presentation.impl.FilePresentationServiceImpl.getFileBackgroundColor(FilePresentationServiceImpl.kt:31)
	at com.intellij.ide.util.treeView.AbstractTreeNode.computeBackgroundColor(AbstractTreeNode.java:275)
	at com.intellij.ide.projectView.ProjectViewNode.computeBackgroundColor(ProjectViewNode.java:298)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:87)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:32)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:486)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:467)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:460)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:418)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:329)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:323)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:343)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:568)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:464)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:430)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:306)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$run
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2023/09/04
 - Plugin version: 2023.5.0/F
 - PhpStorm version: 2023.2.1 (PS-232.9559.64)
 - OS version: Windows 11.0

**Comment by bohdan-harniuk** [comment]
Hi @Bashev ,

Thank you for your report. This issue is related to the PHPStorm native indexes and should not appear after invalidating all indexes: https://www.jetbrains.com/help/phpstorm/invalidate-caches.html

Please, reopen this issue if you need more help here.
Regards,
