### ISSUE TITLE
[Bug]    NewControllerAction#update@ProjectViewPopup (com.atwix.magento.feature.controller.action.NewControllerAction), actionId=Atwix.ContextMenu.NewMagentoController, text='Magento 2 Controller'

### ISSUE THREAD

**Issue by mucan54** [Atwix/phpstorm-plugin-feedback#40]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
*** exception class was changed or removed

   NewControllerAction#update@ProjectViewPopup (com.atwix.magento.feature.controller.action.NewControllerAction), actionId=Atwix.ContextMenu.NewMagentoController, text='Magento 2 Controller'
   
   java.lang.RuntimeException: com.intellij.util.io.CorruptedException: PersistentEnumerator storage corrupted /Users/can/Library/Caches/JetBrains/PhpStorm2023.2/caches/names.dat
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:138)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.lambda$static$0(FSRecordsImpl.java:96)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.handleError(FSRecordsImpl.java:1172)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.getNameByNameId(FSRecordsImpl.java:818)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getNameByNameId(FSRecords.java:316)
	at com.intellij.openapi.vfs.newvfs.persistent.FileNameCache.getVFileName(FileNameCache.java:148)
	at com.intellij.openapi.vfs.newvfs.persistent.FileNameCache.getVFileName(FileNameCache.java:157)
	at com.intellij.openapi.vfs.newvfs.impl.VfsData.getNameByFileId(VfsData.java:221)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.lambda$findIndex$10(VirtualDirectoryImpl.java:783)
	at com.intellij.util.ObjectUtils.binarySearch(ObjectUtils.java:189)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findIndex(VirtualDirectoryImpl.java:783)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChildInArray(VirtualDirectoryImpl.java:101)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:120)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:83)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:532)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:51)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.findFile(PsiDirectoryImpl.java:168)
	at com.atwix.magento.project.util.MagentoModuleUtil.getModuleRegistrationFile(MagentoModuleUtil.java:137)
	at com.atwix.magento.project.util.MagentoModuleUtil.getByDir(MagentoModuleUtil.java:51)
	at com.atwix.magento.feature.controller.action.NewControllerAction.update(NewControllerAction.kt:33)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:159)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:740)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:145)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:240)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$8(ActionUpdater.java:231)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.computeWithSpan(trace.kt:171)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$9(ActionUpdater.java:229)
	at io.opentelemetry.context.Context.lambda$wrapSupplier$8(Context.java:309)
	at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:47)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:193)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:1
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2023/10/02
 - Plugin version: 2023.5.0/F
 - PhpStorm version: 2023.2.1 (PS-232.9559.64)
 - OS version: macOS 13.5.1

**Comment by bohdan-harniuk** [comment]
Hi @mucan54 ,

Please, [invalidate caches](https://www.jetbrains.com/help/idea/invalidate-caches.html) and try to generate controller one more time. It seems to be an internal problem with the PHPStorm caches. If it won't help, please provide the content of the `registration.php` file for the module you are trying to generate controller.

Regards,

**Comment by bohdan-harniuk** [comment]
Hello @mucan54,

We haven't received any updates or additional information regarding this issue in two weeks. As a result, we are assuming this issue is no longer relevant or has been resolved.

We are closing this issue; however, if you encounter the problem again or have more details to provide, please feel free to reopen it. We're here to assist you.

Thank you.

Best regards,
