### ISSUE TITLE
[Bug] java.lang.IllegalArgumentException: Must pass FS root path, but got: 'D:///', which has a parent 'D:'. Use NewVirtualFileSystem.extractRootPath() for obtaining root path

### ISSUE THREAD

**Issue by ioweb-gr** [Atwix/phpstorm-plugin-feedback#43]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
java.lang.IllegalArgumentException: Must pass FS root path, but got: 'D:///', which has a parent 'D:'. Use NewVirtualFileSystem.extractRootPath() for obtaining root path
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findRoot(PersistentFSImpl.java:1495)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.cacheRootsByUrls(PersistentFSImpl.java:1620)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.cacheSingleMissedRootFromPersistence(PersistentFSImpl.java:1602)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$ParentFinder.ascendUntilCachedParent(PersistentFSImpl.java:1685)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$ParentFinder.find(PersistentFSImpl.java:1806)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:1567)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:64)
	at com.intellij.util.indexing.FileBasedIndexImpl.findFileById(FileBasedIndexImpl.java:1184)
	at com.intellij.psi.stubs.StubIndexImplUtil$1.findNext(StubIndexImplUtil.java:36)
	at com.intellij.psi.stubs.StubIndexImplUtil$1.<init>(StubIndexImplUtil.java:22)
	at com.intellij.psi.stubs.StubIndexImplUtil.mapIdIterator(StubIndexImplUtil.java:18)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:182)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:90)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:746)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:1183)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:1160)
	at com.jetbrains.php.PhpIndexImpl.getByFqnCacheAware(PhpIndexImpl.java:1241)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1236)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQN(PhpIndexImpl.java:1225)
	at com.jetbrains.php.PhpClassHierarchyUtils.getSuperClasses(PhpClassHierarchyUtils.java:615)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperClasses(PhpClassImpl.java:502)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperClass(PhpClassImpl.java:496)
	at com.atwix.magento.framework.test.MagentoTestSourceVerifier.getAllSupperClasses(MagentoTestSourceVerifier.java:147)
	at com.atwix.magento.framework.test.MagentoTestSourceVerifier.isTestClass(MagentoTestSourceVerifier.java:128)
	at com.atwix.magento.framework.test.MagentoTestSourceVerifier.isTestSource(MagentoTestSourceVerifier.java:124)
	at com.atwix.magento.framework.test.MagentoTestSourceVerifier.isTestSource(MagentoTestSourceVerifier.java:111)
	at com.atwix.magento.project.configurator.MagentoTestSourceFilterService.isTestSource(MagentoTestSourceFilterService.java:37)
	at com.intellij.openapi.roots.TestSourcesFilter.isTestSources(TestSourcesFilter.java:31)
	at com.intellij.psi.search.scope.TestsScope$1.contains(TestsScope.java:25)
	at com.intellij.psi.search.scope.packageSet.FilteredPackageSet.contains(FilteredPackageSet.java:22)
	at com.intellij.ui.tabs.FileColorsModel.findConfiguration(FileColorsModel.java:246)
	at com.intellij.ui.tabs.FileColorsModel.lambda$getColor$0(FileColorsModel.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.ui.tabs.FileColorsModel.getColor(FileColorsModel.java:211)
	at com.intellij.ui.tabs.FileColorManagerImpl.getFileColor(FileColorManagerImpl.java:166)
	at com.intellij.ui.tabs.EditorTabColorProviderImpl.getProjectViewColor(EditorTabColorProviderImpl.java:31)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getFileBackgroundColor(EditorTabPresentationUtil.kt:47)
	at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.getFileBackgroundColor(VfsPresentationUtil.java:48)
	at com.intellij.presentation.impl.FilePresentationServiceImpl.getFileBackgroundColor(FilePresentationServiceImpl.kt:22)
	at com.intellij.presentation.impl.FilePresentationServiceImpl.getFileBackgroundColor(FilePresentationServiceImpl.kt:31)
	at com.intellij.ide.util.treeView.AbstractTreeNode.computeBackgroundColor(AbstractTreeNode.java:275)
	at com.intellij.ide.projectView.ProjectViewNode.computeBackgroundColor(ProjectViewNode.java:298)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:87)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:32)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:486)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:467)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:460)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:418)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:329)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:323)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:343)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:568)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:464)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:430)
	at com.intellij.util.concurrency.Invok
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2023/10/11
 - Plugin version: 2023.5.1/F
 - PhpStorm version: 2023.2.2 (PS-232.9921.55)
 - OS version: Windows 11.0

**Comment by bohdan-harniuk** [comment]
Hello @ioweb-gr,

Thank you for your report. Could you please provide detailed steps to reproduce this bug?
It would be helpful if you attach content of the file for which that exception was risen.

Regards,

**Comment by bohdan-harniuk** [comment]
Hello @ioweb-gr,

We haven't received any updates or additional information regarding this issue in two weeks. As a result, we are assuming this issue is no longer relevant or has been resolved.

We are closing this issue; however, if you encounter the problem again or have more details to provide, please feel free to reopen it. We're here to assist you.

Thank you.

Best regards,
