### ISSUE TITLE
[Bug] java.lang.Exception

### ISSUE THREAD

**Issue by eufernandodias** [Atwix/phpstorm-plugin-feedback#59]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
Outdated stub in index: file:///var/www/project-enterprise-edition/generated/code/Magento/AdvancedCheckout/Model/Cart/Proxy.php indexing timestamp = 1703189139357, binary = false, byte size = 12573, char size = 12573, doc=DocumentImpl[file:///var/www/project-enterprise-edition/generated/code/Magento/AdvancedCheckout/Model/Cart/Proxy.php], docSaved=true, wasIndexedAlready=true, queried at 1703189139357
doc length=0
file length=0
cached PSI class com.jetbrains.php.lang.psi.PhpFileImpl
projects with file: 1
physical file exists; length = 12573

java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:186)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:152)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:119)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:45)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:625)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:947)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubbedSpine(PsiFileImpl.java:256)
	at com.intellij.psi.stubs.StubProcessingHelperBase.lambda$getAllSpines$0(StubProcessingHelperBase.java:71)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1994)
	at com.intellij.psi.stubs.StubProcessingHelperBase.getAllSpines(StubProcessingHelperBase.java:71)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:152)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:201)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:90)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:746)
	at com.jetbrains.php.PhpIndexImpl.getDirectSubclassesInner(PhpIndexImpl.java:783)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.jetbrains.php.PhpIndexImpl.getDirectSubclasses(PhpIndexImpl.java:779)
	at com.jetbrains.php.PhpIndexImpl.fillAllSubclasses(PhpIndexImpl.java:801)
	at com.jetbrains.php.PhpIndexImpl.fillAllSubclasses(PhpIndexImpl.java:803)
	at com.jetbrains.php.PhpIndexImpl.getAllSubclasses(PhpIndexImpl.java:795)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.subClasses(MemberReferenceImpl.java:311)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.lambda$subclasses$9(MemberReferenceImpl.java:307)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet$SetSpliterator.forEachRemaining(ObjectOpenCustomHashSet.java:630)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at one.util.streamex.AbstractStreamEx.forEach(AbstractStreamEx.java:360)
	at com.jetbrains.php.lang.psi.elements.impl.PhpBaseMemberReference.resolveGlobalDescriptors(PhpBaseMemberReference.java:68)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.resolveGlobalDescriptors(MethodReferenceImpl.java:106)
	at com.jetbrains.php.lang.psi.elements.impl.PhpBaseMemberReference.multiResolve(PhpBaseMemberReference.java:83)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.lambda$getResolver$2(PhpReferenceImpl.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:69)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:159)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:212)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:145)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:153)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.resolve(MethodReferenceImpl.java:149)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.resolve(MethodReferenceImpl.java:144)
	at com.atwix.magento.feature.plugin.inspection.PluginCyclicCallLoopInspection.findWrappedMethodCalls(PluginCyclicCallLoopInspection.kt:99)
	at com.atwix.magento.feature.plugin.inspection.PluginCyclicCallLoopInspection.findWrappedMeth
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2023/12/22
 - Plugin version: 2023.5.2/F
 - PhpStorm version: 2023.3.1 (PS-233.11799.297)
 - OS version: Linux 6.2.0-39-generic

**Comment by bohdan-harniuk** [comment]
Hello @eufernandodias ,

Thank you for bringing this issue to our attention. Upon investigation, it appears that the reported problem is related to PHPStorm's native indexes.

We recommend performing a [cache invalidation](https://www.jetbrains.com/help/idea/invalidate-caches.html) in PHPStorm as a preliminary step to resolve this issue. This process typically resolves transient issues like the one reported, which can occur sporadically due to various factors, such as unexpected shutdowns or other external influences.

As this concern seems to be associated with PHPStorm's native behaviour and does not directly pertain to our plugin, we're marking this matter as closed. However, if after attempting [cache invalidation](https://www.jetbrains.com/help/idea/invalidate-caches.html), the issue persists or if you require further assistance related to our plugin, please feel free to reopen this issue, and we'll be glad to assist you further.

Thank you for your understanding and cooperation.

Best regards,
