### ISSUE TITLE
[Bug] com.intellij.diagnostic.PluginException: 325 ms to call on BGT precache-slow-data@NewControllerAction#update@keyboard shortcut (com.atwix.magento.feature.controller.action.NewControllerAction). Revise AnAction.getActionUpdateThread property [Plugin: com.atwix.magento]

### ISSUE THREAD

**Issue by AymaneTech** [Atwix/phpstorm-plugin-feedback#61]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
com.intellij.diagnostic.PluginException: 325 ms to call on BGT precache-slow-data@NewControllerAction#update@keyboard shortcut (com.atwix.magento.feature.controller.action.NewControllerAction). Revise AnAction.getActionUpdateThread property [Plugin: com.atwix.magento]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.logTimeProblemForPreCached(ActionUpdater.java:487)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.ensureSlowDataKeysPreCached(ActionUpdater.java:481)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$6(ActionUpdater.java:205)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:205)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:165)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:141)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:711)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$UpdateSessionImpl.presentation(ActionUpdater.java:813)
	at com.intellij.openapi.actionSystem.ActionGroupUtil.lambda$getActiveActions$0(ActionGroupUtil.java:31)
	at com.intellij.util.containers.JBIterator$FilterOp.apply(JBIterator.java:314)
	at com.intellij.util.containers.JBIterator.peekNext(JBIterator.java:151)
	at com.intellij.util.containers.JBIterator.hasNext(JBIterator.java:111)
	at com.intellij.util.containers.JBIterable.isEmpty(JBIterable.java:762)
	at com.intellij.openapi.actionSystem.ActionGroupUtil.isGroupEmpty(ActionGroupUtil.java:14)
	at com.intellij.ide.actions.NewElementAction.update(NewElementAction.java:87)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:158)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:181)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:726)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:140)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$5(ActionUpdater.java:190)
	at com.intellij.diagnostic.telemetry.TraceKt.computeWithSpan(trace.kt:123)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:186)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:165)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:141)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:711)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$UpdateSessionImpl.presentation(ActionUpdater.java:813)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doUpdateActionsInner(IdeKeyEventDispatcher.java:675)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:622)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$15(Utils.java:753)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$19(ActionUpdater.java:425)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:421)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$16(Utils.java:753)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$18(Utils.java:760)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$20(Utils.java:759)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorke
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2024/01/11
 - Plugin version: 2023.5.1/F
 - PhpStorm version: 2023.1.3 (PS-231.9161.47)
 - OS version: Windows 11.0

**Comment by bohdan-harniuk** [comment]
Hello @AymaneTech ,

Thank you for taking the time to report this issue. We greatly appreciate your contribution to improving our project.

Our team is now reviewing the problem, and we'll work on resolving it as quickly as possible. We will keep you updated on our progress, and if we have any questions or need more information from you, we'll reach out.

Once again, thank you for your report, and we'll do our best to address this issue promptly.

Best regards,

**Comment by bohdan-harniuk** [comment]
Hello @AymaneTech,

The reported bug has been resolved in the next release version of the plugin (2023.5.2). Please update your plugin to the latest available version to get much more useful features (2024.1.0). 
Thank you for reporting this issue! If you encounter any issues or have more feedback, please let us know.

Thank you,

**Comment by AymaneTech** [comment]
Hello @bohdan-harniuk  

Thank you for acknowledging my report. I'm glad to know that the issue is being taken seriously and that your team is actively working on resolving it. I appreciate the transparency in keeping me updated on the progress.

Please feel free to reach out if there's any additional information or assistance I can provide to expedite the resolution process.

Looking forward to hearing about the updates soon.

Best regards,
