### ISSUE TITLE
[Bug] java.lang.AssertionError: record(1894884).fileId(300573) != backref fileId(-1), AttributesRecord[dedicated][0..0, length: 0][backRefFileId: -1, dedicatedAttributeId: -1]

### ISSUE THREAD

**Issue by aganganna-usgb** [Atwix/phpstorm-plugin-feedback#62]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
java.lang.AssertionError: record(1894884).fileId(300573) != backref fileId(-1), AttributesRecord[dedicated][0..0, length: 0][backRefFileId: -1, dedicatedAttributeId: -1]
	at com.intellij.openapi.vfs.newvfs.persistent.AttributesStorageOverBlobStorage.lambda$readAttributeValue$6(AttributesStorageOverBlobStorage.java:997)
	at com.intellij.openapi.vfs.newvfs.persistent.dev.blobstorage.StreamlinedBlobStorageOverMMappedFile.readRecord(StreamlinedBlobStorageOverMMappedFile.java:219)
	at com.intellij.openapi.vfs.newvfs.persistent.dev.blobstorage.StreamlinedBlobStorageHelper.readRecord(StreamlinedBlobStorageHelper.java:216)
	at com.intellij.openapi.vfs.newvfs.persistent.AttributesStorageOverBlobStorage.readAttributeValue(AttributesStorageOverBlobStorage.java:995)
	at com.intellij.openapi.vfs.newvfs.persistent.AttributesStorageOverBlobStorage.readAttribute(AttributesStorageOverBlobStorage.java:100)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSAttributeAccessor.readAttribute(PersistentFSAttributeAccessor.java:34)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.readAttribute(FSRecordsImpl.java:1185)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.readAttributeWithLock(FSRecordsImpl.java:1175)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.readAttribute(PersistentFSImpl.java:425)
	at com.intellij.openapi.vfs.newvfs.FileAttribute.readFileAttribute(FileAttribute.java:72)
	at com.intellij.openapi.fileTypes.impl.FileTypeDetectionService.readFlagsFromCache(FileTypeDetectionService.java:332)
	at com.intellij.openapi.fileTypes.impl.FileTypeDetectionService.getOrDetectFromContent(FileTypeDetectionService.java:218)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.internalContinueToDetectFileTypeByFile(FileTypeManagerImpl.java:764)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:755)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:695)
	at com.intellij.openapi.vfs.VirtualFile.getFileType(VirtualFile.java:356)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getFileType(VirtualFileSystemEntry.java:622)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1360)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1317)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1682)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1676)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1699)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:788)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:296)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFilesIterator(FileBasedIndexEx.java:244)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFiles(FileBasedIndexEx.java:220)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:1073)
	at com.atwix.magento.indexing.provider.WebApiIndexProvider.getServiceDeclaration(WebApiIndexProvider.kt:26)
	at com.atwix.magento.feature.webapi.navigation.lineMarker.GoToWebApiDeclarationLineMarkerProvider.getLineMarkerInfo(GoToWebApiDeclarationLineMarkerProvider.kt:46)
	at com.atwix.magento.feature.webapi.navigation.lineMarker.GoToWebApiDeclarationLineMarkerProvider.getLineMarkerInfo(GoToWebApiDeclarationLineMarkerProvider.kt:29)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:183)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectMarkers$2(LineMarkersPass.java:107)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:98)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectMarkers(LineMarkersPass.java:103)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:76)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:406)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:76)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:34)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:401)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.jav
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2024/01/18
 - Plugin version: 2023.5.3/F
 - PhpStorm version: 2023.3.2 (PS-233.13135.108)
 - OS version: macOS 13.5.2

**Comment by bohdan-harniuk** [comment]
Hello @aganganna-usgb ,

Thank you for your report. This issue is related to the PHPStorm native indexes and should not appear after invalidating all indexes: https://www.jetbrains.com/help/phpstorm/invalidate-caches.html

If you encounter any issues or have more feedback, please let us know.
