### ISSUE TITLE
[Bug] java.lang.AssertionError: 0 : child= 'FilePartNode: 'PrintLabel.php'; children: 0; fs=LocalFileSystem; myFileOrUrl=file:///Users/mehdi/Development/commer/kadolin-magento/app/code/Sana/Forward/Controller/Adminhtml/Order/PrintLabel.php; class java.lang.String'; child.nameEqualTo(nameId)=false; child.getClass()=class com.intellij.openapi.vfs.impl.FilePartNode; child.nameId=866916; child.getName()='PrintLabel.php'; nameId=1960581; name='Printlabel.php'; compare(child) = 0; UrlPart.nameEquals: true; name.equals(child.getName())=false; file=file:///Users/mehdi/Development/commer/kadolin-magento/app/code/Sana/Forward/Controller/Adminhtml/Order/Printlabel.php; this.isCaseSensitive()=false

### ISSUE THREAD

**Issue by alikhani97** [Atwix/phpstorm-plugin-feedback#63]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
java.lang.AssertionError: 0 : child= 'FilePartNode: 'PrintLabel.php'; children: 0; fs=LocalFileSystem; myFileOrUrl=file:///Users/mehdi/Development/commer/kadolin-magento/app/code/Sana/Forward/Controller/Adminhtml/Order/PrintLabel.php; class java.lang.String'; child.nameEqualTo(nameId)=false; child.getClass()=class com.intellij.openapi.vfs.impl.FilePartNode; child.nameId=866916; child.getName()='PrintLabel.php'; nameId=1960581; name='Printlabel.php'; compare(child) = 0; UrlPart.nameEquals: true; name.equals(child.getName())=false; file=file:///Users/mehdi/Development/commer/kadolin-magento/app/code/Sana/Forward/Controller/Adminhtml/Order/Printlabel.php; this.isCaseSensitive()=false
	at com.intellij.openapi.vfs.impl.FilePartNode.findChildByNameId(FilePartNode.java:174)
	at com.intellij.openapi.vfs.impl.FilePartNodeRoot.matchById(FilePartNodeRoot.java:123)
	at com.intellij.openapi.vfs.impl.FilePartNodeRoot.findOrCreateByFile(FilePartNodeRoot.java:51)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl.getOrCreate(VirtualFilePointerManagerImpl.java:389)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl.create(VirtualFilePointerManagerImpl.java:276)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl.create(VirtualFilePointerManagerImpl.java:192)
	at com.intellij.openapi.fileEditor.impl.HistoryEntry.createHeavy(HistoryEntry.java:98)
	at com.intellij.openapi.fileEditor.impl.EditorHistoryManager.fileOpenedImpl(EditorHistoryManager.java:143)
	at com.intellij.openapi.fileEditor.impl.EditorHistoryManager.updateHistoryEntry(EditorHistoryManager.java:184)
	at com.intellij.openapi.fileEditor.impl.EditorHistoryManager.updateHistoryEntry(EditorHistoryManager.java:152)
	at com.intellij.openapi.fileEditor.impl.EditorHistoryManager$MyEditorManagerListener.lambda$selectionChanged$0(EditorHistoryManager.java:396)
	at com.intellij.psi.impl.PsiDocumentManagerBase.performWhenAllCommitted(PsiDocumentManagerBase.java:589)
	at com.intellij.psi.impl.PsiDocumentManagerBase.performWhenAllCommitted(PsiDocumentManagerBase.java:579)
	at com.intellij.openapi.fileEditor.impl.EditorHistoryManager$MyEditorManagerListener.selectionChanged(EditorHistoryManager.java:385)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:655)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:621)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:395)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:374)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:433)
	at jdk.proxy1/jdk.proxy1.$Proxy137.selectionChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$fireSelectionChanged$25(FileEditorManagerImpl.java:1815)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$7.lambda$run$0(FileEditorManagerImpl.java:1252)
	at com.intellij.openapi.util.ExpirableRunnable$1.run(ExpirableRunnable.java:17)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:173)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:33)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:176)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:129)
	at com.intellij.openapi.wm.impl.
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2024/01/23
 - Plugin version: 2023.5.0/F
 - PhpStorm version: 2022.3.3 (PS-223.8836.42)
 - OS version: macOS 14.2.1

**Comment by bohdan-harniuk** [comment]
Hello @alikhani97,

Thank you for your report. This issue is related to the PHPStorm native functionality and should not appear after invalidating all indexes: https://www.jetbrains.com/help/phpstorm/invalidate-caches.html

If you encounter any issues or have more feedback, please let us know.
