### ISSUE TITLE
[Bug] java.lang.Throwable: Stub index points to a file (file = file:///home/suryano/Documentos/trabalho/ELFA_Ecom_Magento2_PWA/generated/code/Magento/ConfigurableProduct/Api/Data/OptionExtensionInterface.php, file type = com.jetbrains.php.lang.PhpFileType@36bcf8d7, indexed file type = null) without indexed stub tree; indexing stamp = indexing timestamp = 1712096394139, binary = false, byte size = 253, char size = 253, can have stubs = true, actual stub count = 0

### ISSUE THREAD

**Issue by cordeirofilho** [Atwix/phpstorm-plugin-feedback#75]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
java.lang.Throwable: Stub index points to a file (file = file:///home/suryano/Documentos/trabalho/ELFA_Ecom_Magento2_PWA/generated/code/Magento/ConfigurableProduct/Api/Data/OptionExtensionInterface.php, file type = com.jetbrains.php.lang.PhpFileType@36bcf8d7, indexed file type = null) without indexed stub tree; indexing stamp = indexing timestamp = 1712096394139, binary = false, byte size = 253, char size = 253, can have stubs = true, actual stub count = 0
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:37)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$6(StubIndexEx.java:196)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:195)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:90)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:746)
	at com.jetbrains.php.PhpIndexImpl.getDirectSubclassesInner(PhpIndexImpl.java:783)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
	at com.jetbrains.php.PhpIndexImpl.getDirectSubclasses(PhpIndexImpl.java:779)
	at com.jetbrains.php.PhpIndexImpl.fillAllSubclasses(PhpIndexImpl.java:801)
	at com.jetbrains.php.PhpIndexImpl.getAllSubclasses(PhpIndexImpl.java:795)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.subClasses(MemberReferenceImpl.java:311)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.lambda$subclasses$9(MemberReferenceImpl.java:307)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at one.util.streamex.AbstractStreamEx.forEach(AbstractStreamEx.java:360)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.withSuperClasses(MemberReferenceImpl.java:294)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.lookInSubclasses(MemberReferenceImpl.java:284)
	at com.jetbrains.php.lang.psi.elements.impl.PhpBaseMemberReference.resolveGlobalDescriptors(PhpBaseMemberReference.java:68)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.resolveGlobalDescriptors(MethodReferenceImpl.java:106)
	at com.jetbrains.php.lang.psi.elements.impl.PhpBaseMemberReference.multiResolve(PhpBaseMemberReference.java:83)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.lambda$getResolver$2(PhpReferenceImpl.java:160)
	at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:69)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:159)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:212)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:145)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:153)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.resolve(MethodReferenceImpl.java:149)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.resolve(MethodReferenceImpl.java:144)
	at com.atwix.magento.feature.cli.parser.CliCommandParser.resolveFromMethodCallArgument(CliCommandParser.kt:61)
	at com.atwix.magento.feature.cli.parser.CliCommandParser.resolveCommandName(CliCommandParser.kt:37)
	at com.atwix.magento.feature.cli.parser.CliCommandParser.parse(CliCommandParser.kt:29)
	at com.atwix.magento.feature.cli.parser.CliCommandParser.parse(CliCommandParser.kt:24)
	at com.atwix.magento.feature.cli.index.CliCommandIndexProvider.parseCliCommands(CliCommandIndexProvider.kt:69)
	at com.atwix.magento.feature.cli.index.CliCommandIndexProvider$refreshCliCommandsCache$1.invokeSuspend$lambda$0(CliCommandIndexProvider.kt:50)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.app
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2024/04/03
 - Plugin version: 2024.1.1/F
 - PhpStorm version: 2023.3.6 (PS-233.15026.12)
 - OS version: Linux 6.5.0-26-generic

**Comment by bohdan-harniuk** [comment]
Hello @cordeirofilho,

Thank you for your report. This issue pertains to PHPStorm's native indexes and should not occur regularly. If you encounter it repeatedly, you can invalidate all indexes: https://www.jetbrains.com/help/phpstorm/invalidate-caches.html. 

If you encounter any issues or have more feedback, please let us know.
