### ISSUE TITLE
[Bug] java.lang.Exception

### ISSUE THREAD

**Issue by quterorta** [Atwix/phpstorm-plugin-feedback#81]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
Outdated stub in index: file:////wsl.localhost/Ubuntu/home/quterorta/Sites/moto/generated/code/Magento/MessageQueue/Console/StartConsumerCommand/Proxy.php, vFileId=560723, indexing timestamp = 1715952474648, binary = false, byte size = 7384, char size = 7384, doc=DocumentImpl[file:////wsl.localhost/Ubuntu/home/quterorta/Sites/moto/generated/code/Magento/MessageQueue/Console/StartConsumerCommand/Proxy.php], docSaved=true, wasIndexedAlready=true, queried at 1715952474648
doc length=0
file length=0
cached PSI class com.jetbrains.php.lang.psi.PhpFileImpl
PSI length=0
projects with file: 1
physical file doesn't exist; length = \\wsl.localhost\Ubuntu\home\quterorta\Sites\moto\generated\code\Magento\MessageQueue\Console\StartConsumerCommand\Proxy.php

java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:188)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:152)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:119)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.doCreateCompleteException(StubTreeLoader.java:184)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.lambda$createCompleteException$0(StubTreeLoader.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:277)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:277)
	at com.intellij.psi.stubs.StubTreeLoader$StubTreeAndIndexUnmatchCoarseException.createCompleteException(StubTreeLoader.java:177)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:227)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:733)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:126)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getFirstChild(ASTDelegatePsiElement.java:87)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:32)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:14)
	at com.intellij.util.WalkingState.next(WalkingState.java:70)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:49)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:40)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:62)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:34)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:939)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:120)
	at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:935)
	at com.intellij.psi.util.PsiTreeUtil.findChildrenOfAnyType(PsiTreeUtil.java:313)
	at com.intellij.psi.util.PsiTreeUtil.findChildrenOfType(PsiTreeUtil.java:278)
	at com.atwix.magento.feature.cli.parser.CliCommandParser.parse(CliCommandParser.kt:29)
	at com.atwix.magento.feature.cli.parser.CliCommandParser.parse(CliCommandParser.kt:25)
	at com.atwix.magento.feature.cli.index.CliCommandIndexProvider.parseCliCommands(CliCommandIndexProvider.kt:69)
	at com.atwix.magento.feature.cli.index.CliCommandIndexProvider$refreshCliCommandsCache$1.invokeSuspend$lambda$0(CliCommandIndexProvider.kt:50)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:289)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:850)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.atwix.magento.feature.cli.index.CliCommandIndexProvider$refreshCliCommandsCache$1.invokeSuspend(CliCommandIndexProvider.kt:50)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2024/05/23
 - Plugin version: 2024.1.3/F
 - PhpStorm version: 2024.1 (PS-241.14494.237)
 - OS version: Windows 11.0

**Comment by bohdan-harniuk** [comment]
Hello @quterorta,

The reported problem is related to PHPStorm's native indexes. This issue is transient and can occur sporadically due to various factors, such as unexpected shutdowns or other external influences.

As this concern seems to be associated with PHPStorm's native behaviour and does not directly pertain to our plugin, we're marking this matter as closed. However, if after attempting [cache invalidation](https://www.jetbrains.com/help/idea/invalidate-caches.html), the issue persists or if you require further assistance related to our plugin, please feel free to reopen this issue, and we'll be glad to assist you further.

Best regards,
