### ISSUE TITLE
[Bug] java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize

### ISSUE THREAD

**Issue by alkeshrohit22** [Atwix/phpstorm-plugin-feedback#88]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:250)
	at com.intellij.ui.jcef.JBCefBrowserBase.lambda$new$3(JBCefBrowserBase.java:152)
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java:124)
	at com.intellij.ui.jcef.JBCefBrowserBase.<init>(JBCefBrowserBase.java:152)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:190)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:150)
	at com.atwix.magento.feature.chatgpt.window.ChatGPTWidgetToolWindow.<init>(ChatGPTWidgetToolWindow.kt:20)
	at com.atwix.magento.feature.chatgpt.window.ChatGPTWidgetToolWindowFactory.createToolWindowContent(ChatGPTWidgetToolWindowFactory.kt:21)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:543)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:522)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1009)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:946)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:662)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow(ToolWindowManagerImpl.kt:622)
	at com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager.activateToolWindow(BackendServerToolWindowManager.kt:188)
	at com.intellij.ide.actions.ToolwindowSwitcher$ToolWindowAction.actionPerformed(ToolwindowSwitcher.java:160)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:327)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:306)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:350)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:306)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:528)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:252)
	at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$1(ActionPopupStep.java:229)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$17(AbstractPopup.java:1585)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:173)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:33)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:176)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:129)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:169)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:163)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1583)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:165)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:377)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:288)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:127)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:243)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:231)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:273)
	at com.intellij.ui.popup.list.ListPopupImpl.disposePopup(ListPopupImpl.java:470)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:497)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:464)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:412)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.handleSelect(PopupFactoryImpl.java:300)
	at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:666)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:731)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.j
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2024/06/22
 - Plugin version: 2023.5.0/F
 - PhpStorm version: 2022.3.3 (PS-223.8836.42)
 - OS version: Linux 5.15.0-107-generic

**Comment by bohdan-harniuk** [comment]
Hello @alkeshrohit22,

Thank you for taking the time to report this issue. We greatly appreciate your contribution to improving our project.

Our team is now reviewing the problem, and we'll work on resolving it as quickly as possible. We will keep you updated on our progress, and if we have any questions or need more information from you, we'll reach out.

Once again, thank you for your report, and we'll do our best to address this issue promptly.

Best regards,

**Comment by ioweb-gr** [comment]
Hi,
for me the IDE is unusable with your plugin active after upgrading phpstorm to latest version. I've already done cache invalidation / restart and no change whatsoever. For me the only solution is to disable the plugin entirely

**Comment by bohdan-harniuk** [comment]
Hi @ioweb-gr ,

It looks like you're using version 2023.5.0 of the plugin, which isn't compatible with PHPStorm 2024.2. To resolve this, please update PHPStorm to the latest version and then install the 2024.2.0 version of the plugin.

Best regards,

**Comment by bohdan-harniuk** [comment]
@ioweb-gr ,
It looks like your comment may have been posted in the wrong issue. Let's continue our discussion, if needed, in the correct thread here: https://github.com/Atwix/phpstorm-plugin-feedback/issues/94

**Comment by bohdan-harniuk** [comment]
Hello @alkeshrohit22 ,

The issue you're encountering is related to an incorrect Boot Java Runtime in your IDE. From what I can see, JCEF (Java Chromium Embedded Framework, internal browser) is available in your current PhpStorm version:

![Screenshot 2024-09-05 at 16 09 39](https://github.com/user-attachments/assets/f988bcd0-090d-432e-9895-9f89296e68a5)

However, you're using PhpStorm 2022.3.3, which was released on March 13, 2023. This is an older version, and by using it, you're missing out on many features both in PhpStorm and our plugin. I highly recommend updating to the latest version of PhpStorm, and ensuring our plugin is also updated (this should happen automatically).

To resolve this specific issue on your current PhpStorm version, ensure you are using a runtime that supports JCEF. To do this:

1. Go to **Help | Find Action** in the PhpStorm main menu.
2. Search for **"Choose Boot Java Runtime for the IDE"** and select it.
3. Choose the latest bundled runtime with JCEF support.
4. Click **OK** and **restart** the IDE.

![Screenshot 2024-09-05 at 16 05 42](https://github.com/user-attachments/assets/82cd9f59-5d71-414e-a9ec-81456b1cc0a3)

However, please note that this issue occurred while trying to use the ChatGPT widget, which runs via the internal IDE browser. This feature has been discontinued and fully removed in the latest version of our plugin (2024.2.0). We made this change because JetBrains has developed a superior alternative, which you can check out here: https://www.jetbrains.com/ai/. Our focus is on improving the development experience for Adobe Commerce/Magento/MageOS, leaving AI-related functionalities to JetBrains' dedicated solution.

Best regards,

**Comment by alkeshrohit22** [comment]
Okay, Let me change the settings.

Thanks & Regards,
*Alkesh Rohit*
Associate Software Engineer
Sigma Infosolutions Ltd. A TUV Certified ISO 9001:2015 and ISO 27001:2013
Company
***@***.***
