### ISSUE TITLE
[Bug] java.lang.AssertionError: PSI can be created only for a file with LanguageFileType but actual is class com.intellij.openapi.fileTypes.impl.DetectedByContentFileType.

### ISSUE THREAD

**Issue by ioweb-gr** [Atwix/phpstorm-plugin-feedback#95]
**Describe the bug** (*)

This bug comes up for me when I try to run code inspections for a module. 

**StackTrace from IDE**

```
java.lang.AssertionError: PSI can be created only for a file with LanguageFileType but actual is class com.intellij.openapi.fileTypes.impl.DetectedByContentFileType.
Please use a proper FileBasedIndexExtension#getInputFilter() implementation for the caller index
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:77)
	at com.intellij.util.indexing.FileContentImpl.getPsiFile(FileContentImpl.java:232)
	at com.atwix.magento.indexing.processor.TranslationIndex$getIndexer$1.map(TranslationIndex.kt:32)
	at com.atwix.magento.indexing.processor.TranslationIndex$getIndexer$1.map(TranslationIndex.kt:31)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:318)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:309)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:250)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.updateBaseIndex(CompositeInvertedIndexBase.java:288)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:65)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:30)
	at com.intellij.util.indexing.FileBasedIndexImpl.createSingleIndexValueApplier(FileBasedIndexImpl.java:1634)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$23(FileBasedIndexImpl.java:1504)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.lambda$freezeFileTypeTemporarilyWithProvidedValueIn$15(FileTypeManagerImpl.java:738)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:734)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1457)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1431)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1374)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1746)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1740)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1763)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:846)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:358)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:168)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:107)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:95)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:753)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:1190)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:1167)
	at com.jetbrains.php.PhpIndexImpl.getByFqnCacheAware(PhpIndexImpl.java:1248)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1243)
	at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:1282)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:898)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:835)
	at com.jetbrains.php.PhpIndexImpl.doCompleteType(PhpIndexImpl.java:205)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:131)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:104)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:1077)
	at com.jetbrains.php.lang.psi.elements.PhpTypedElement.getGlobalType(PhpTypedElement.java:57)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveInHierarchyInner(MemberReferenceImpl.java:194)
	at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.lambda$resolveInHierarchy$1(MemberReferenceImpl.java:187)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:173)
	at com.intellij.psi.impl.PsiCachedValueImpl$Direct.doCompute(PsiCachedValueImpl.kt:77)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:236)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueW
```

**To Reproduce** (*)

**Screenshots**

**System information:**

 - Occurred: 2024/09/07
 - Plugin version: 2024.2.0/L
 - PhpStorm version: 2024.2.1 (PS-242.21829.154)
 - OS version: Windows 11.0

**Comment by bohdan-harniuk** [comment]
Hello @ioweb-gr ,

Please navigate to **Settings | Editor | File Types** and verify the value for **CSV/TSV** data under the **Recognized File Types** tab. The file type `*.csv` should be listed there.

![image](https://github.com/user-attachments/assets/069d9609-23b7-4db5-9fcc-4e5931c328c9)

The exception you encountered has been addressed in our plugin, and the fix will be available in the upcoming 2024.2.1 release. This update will prevent the exception from being thrown, but to ensure that CSV file types (including those used by our plugin) function properly in PhpStorm, please confirm that `*.csv` is included in the setting mentioned earlier. If it's missing, simply add it, and the exception should no longer occur.

Best regards,

**Comment by ioweb-gr** [comment]
Indeed the association was lost. Thank you :)

**Comment by bohdan-harniuk** [comment]
@ioweb-gr , 

I'm happy to assist you with this. I'm marking this task as resolved. The additional check to address the critical error reported during indexing has been completed and will be released soon.

Best regards,
