### ISSUE TITLE
[Bug] Read access is allowed from inside read-action only in ControllerSEContributor.kt:77

### ISSUE THREAD

**Issue by robson-bn** [Atwix/phpstorm-plugin-feedback#97]
**Describe the bug** (*)

Please, describe as much as possible about of what the bug is. It will help to solve this issue faster.

**StackTrace from IDE**

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction  or ReadAction; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#35032,SE-SearchTask-ControllerSEContributor,4,main] 1816038659 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#78,AWT-EventQueue-0,6,main] 1641919549
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:218)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:921)
	at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:197)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTreeOrFileElement(PsiFileImpl.java:708)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:645)
	at com.intellij.psi.impl.source.SpineRef.getGreenStub(SpineRef.java:33)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:346)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getParent(StubBasedPsiElementBase.java:311)
	at com.intellij.util.xml.model.gotosymbol.GoToSymbolProvider$BaseNavigationItem.getParent(GoToSymbolProvider.java:158)
	at com.intellij.psi.impl.FakePsiElement.getManager(FakePsiElement.java:131)
	at org.jetbrains.kotlin.idea.searcheverywhere.KtSearchEverywhereEqualityProvider$Companion.compareElements$lambda$2(KtSearchEverywhereEqualityProvider.kt:67)
	at org.jetbrains.kotlin.idea.searcheverywhere.KtSearchEverywhereEqualityProvider$Companion.compareElements$reduce$lambda$0(KtSearchEverywhereEqualityProvider.kt:58)
	at kotlin.sequences.TransformingIndexedSequence$iterator$1.next(Sequences.kt:234)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:172)
	at org.jetbrains.kotlin.idea.searcheverywhere.KtSearchEverywhereEqualityProvider$Companion.compareElements$reduce(KtSearchEverywhereEqualityProvider.kt:60)
	at org.jetbrains.kotlin.idea.searcheverywhere.KtSearchEverywhereEqualityProvider$Companion.compareElements(KtSearchEverywhereEqualityProvider.kt:63)
	at org.jetbrains.kotlin.idea.searcheverywhere.KtSearchEverywhereEqualityProvider.compareItems(KtSearchEverywhereEqualityProvider.kt:28)
	at com.intellij.ide.actions.searcheverywhere.SEResultsEqualityProvider$Companion$composite$1.compareItems$lambda$0(SEResultsEqualityProvider.kt:74)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at com.intellij.ide.actions.searcheverywhere.SEResultsEqualityProvider$Companion$composite$1.compareItems(SEResultsEqualityProvider.kt:86)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ResultsAccumulator.addElement(MixedResultsSearcher.java:322)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.processFoundItem(MixedResultsSearcher.java:222)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.lambda$run$0(MixedResultsSearcher.java:183)
	at com.atwix.magento.feature.controller.action.searcheverywhere.ControllerSEContributor.fetchWeightedElements(ControllerSEContributor.kt:77)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:182)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:206)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$1.run(AnyThreadWriteThreadingSupport.kt:167)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.lambda$call$1(ContextCallable.java:74)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:83)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**To Reproduce** (*)

1. Just open a Magento project into IDE.

**Screenshots**

**System information:**

 - Occurred: 2024/11/26
 - Plugin version: 2024.3.0/L
 - IntelliJ IDEA version: 2024.3 (IU-243.21565.193)
 - OS version: Linux 6.8.0-48-generic

**Comment by bohdan-harniuk** [comment]
Hello @robson-bn,

Thank you for taking the time to report this issue. We greatly appreciate your contribution to improving our project.

Our team is now reviewing the problem, and we'll work on resolving it as quickly as possible. We will keep you updated on our progress, and if we have any questions or need more information from you, we'll reach out.

Once again, thank you for your report, and we'll do our best to address this issue promptly.

Best regards,

**Comment by bohdan-harniuk** [comment]
Hello @robson-bn ,

**Fixed and Coming Soon!**

The reported bug has been fixed and will be available in our upcoming release. Thank you for bringing it to our attention! 

If you encounter any issues or have more feedback, please let us know.

**Comment by bohdan-harniuk** [comment]
Hi @robson-bn,

Kindly update to the latest available version (2025.1.0), which includes a fix for this issue along with several other exciting features.

Best regards,
