### ISSUE TITLE
[Bug] Method getUseScope is not yet implemented in I18nReference.wrapPhraseInElement

### ISSUE THREAD

**Issue by rsantos-dh** [Atwix/phpstorm-plugin-feedback#98]
**Describe the bug** (*)

Just open a Magento 2 project

**StackTrace from IDE**

```
java.lang.UnsupportedOperationException: Method getUseScope is not yet implemented in com.atwix.magento.feature.i18n.reference.I18nReference$wrapPhraseInElement$1
	at com.atwix.magento.lang.MockPsiElement.getUseScope(MockPsiElement.kt:224)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.getUseScope(PsiSearchHelperImpl.java:92)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.getUseScope(PsiSearchHelperImpl.java:81)
	at com.intellij.psi.search.searches.ReferencesSearch$SearchParameters.getEffectiveSearchScope(ReferencesSearch.java:97)
	at com.intellij.psi.impl.search.SPIReferencesSearcher.processQuery(SPIReferencesSearcher.java:26)
	at com.intellij.psi.impl.search.SPIReferencesSearcher.processQuery(SPIReferencesSearcher.java:16)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:76)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:30)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:83)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:100)
	at com.intellij.util.MergeQuery.processResults(MergeQuery.java:22)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:83)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:100)
	at com.intellij.util.UniqueResultsQuery.processResults(UniqueResultsQuery.java:37)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:83)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.AbstractQuery.findAll(AbstractQuery.java:24)
	at com.intellij.codeInsight.highlighting.HighlightUsagesKt.getPsiUsageRanges(highlightUsages.kt:85)
	at com.intellij.codeInsight.highlighting.HighlightUsagesKt.getUsageRanges(highlightUsages.kt:65)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.lambda$highlightTargetUsages$1(IdentifierHighlighterPass.java:256)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:171)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:129)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:113)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightTargetUsages(IdentifierHighlighterPass.java:255)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightReferencesAndDeclarations(IdentifierHighlighterPass.java:228)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.lambda$doCollectInformation$0(IdentifierHighlighterPass.java:108)
	at com.intellij.openapi.project.DumbService.withAlternativeResolveEnabled(DumbService.kt:339)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:107)
	at com.intellij.codeInsight.highlighting.BackgroundHighlighterKt.submitIdentifierHighlighterPass$lambda$17$lambda$16$lambda$14(BackgroundHighlighter.kt:409)
	at com.intellij.codeInsight.highlighting.BackgroundHighlighterKt.submitIdentifierHighlighterPass$lambda$17$lambda$16$lambda$15(BackgroundHighlighter.kt:409)
	at com.intellij.codeInsight.daemon.impl.HighlightingSessionImpl.runInsideHighlightingSession(HighlightingSessionImpl.java:182)
	at com.intellij.codeInsight.highlighting.BackgroundHighlighterKt.submitIdentifierHighlighterPass$lambda$17$lambda$16(BackgroundHighlighter.kt:406)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:140)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:137)
	at com.intellij.codeInsight.highlighting.BackgroundHighlighterKt.submitIdentifierHighlighterPass$lambda$17(BackgroundHighlighter.kt:402)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:857)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:889)
	at com.intellij.openapi.application.impl.NonBlockingReadAc
```

**To Reproduce** (*)

1. Just open a Magento 2 project

**Screenshots**

**System information:**

 - Occurred: 2024/12/17
 - Plugin version: 2024.3.1/L
 - IntelliJ IDEA version: 2024.3.1 (IU-243.22562.145)
 - OS version: Linux 6.8.0-50-generic

**Comment by bohdan-harniuk** [comment]
Hello @rsantos-dh ,

Thank you for taking the time to report this issue. We greatly appreciate your contribution to improving our project.

Our team is now reviewing the problem, and we'll work on resolving it as quickly as possible. We will keep you updated on our progress, and if we have any questions or need more information from you, we'll reach out.

Once again, thank you for your report, and we'll do our best to address this issue promptly.

Best regards,

**Comment by bohdan-harniuk** [comment]
Hi @rsantos-dh ,

I was unable to reproduce this issue. Could you please share a screenshot of your IDE information? You can find it under `PhpStorm > About PhpStorm`.

Additionally, could you provide a list of the third-party plugins you have installed? You can find this list in `PhpStorm > Settings > Plugins > Installed > Downloaded`.

Thank you!

**Comment by bohdan-harniuk** [comment]
Hi @rsantos-dh ,

We haven’t heard back on this issue in a while, so we’re going to close it for now. If you’re still experiencing the problem or have more details to share, feel free to reopen this issue or create a new one - we’re happy to take another look.

Thank you!
